main: dev.waitpvp.ha.main.Main
name: ParticleKillEffects
version: 1.8.8-ASHS.NTUN
author: WaitNetwork-Development
description: A plugin of Particle Kill Effect. FOR WAIT NETWORK.
commands:
  killeffect:
    description: MAIN COMMMMMMMMMABNDA SDADASASDASDADADAD ADASDAS
    aliases:
      - ke
      - k