name: WaitKillEffect
main: dev.yudong.effectkill.Main
author: YuDong
description: A simple effect plugin when Player death. this is so shit
version: 1.2
commands:
  killeffect:
    aliases: [ke, ek, kille, shit, pke]